version: '3.9'

services:
  api:
    build: client_api/
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    env_file:
#      - .env
      - .env-shared
  searcher:
    build: searcher/
    depends_on:
      - db
    env_file:
#      - .env
      - .env-shared
  bot:
    build: searcher/
    depends_on:
      - db
    env_file:
#      - .env
      - .env-shared
  db:
    image: postgres:latest
    restart: on-failure
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
#      - ./data/db:/var/lib/postgresql/data
      - ./sql_scripts:/docker-entrypoint-initdb.d
    env_file:
#      - .env
      - .env-shared
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "${PGADMIN_PORT}:80"
    env_file:
#      - .env
      - .env-shared